ALTER TABLE `wz`.`health` 
ADD COLUMN `szy` DOUBLE NOT NULL COMMENT '舒张压' AFTER `createTime`,
ADD COLUMN `ssy` DOUBLE NOT NULL COMMENT '收缩压' AFTER `szy`;

ALTER TABLE `wz`.`health` 
CHANGE COLUMN `szy` `szy` DOUBLE NOT NULL DEFAULT 0 COMMENT '舒张压' ,
CHANGE COLUMN `ssy` `ssy` DOUBLE NOT NULL DEFAULT 0 COMMENT '收缩压' ;

